### PR TITLE
pilight config parsing added

### PR DESCRIPTION
**Pull request by thejatom**

### CODE REVIEW

**Comment by sweetpi** [comment]
How is now the state of pilight 7 support?

**Comment by thejatom** [comment]
The state is that we can connect and read the configuration
And the plugin keeps the connection and support switches (mostly because I
have no other devices controlled by plight)
2 lis 2015 8:12 AM "sweet pi - sweet home" <notifications@github.com>
napisał(a):

**Comment by sweetpi** [comment]
I updated the Readme with the info. Do you want to maintain the plugin and/or adding support for more device types?

**Comment by thejatom** [comment]
I modified the messages that are sent for all kind of devices. 
The clue is that we are not sending "message": "send" anymore, but "action": "control". 
For switches it was only this change so maybe for other devices as well
It is hard to test by me because I don't have any other types of devices connected to my pilight, so is there a chance that someone else could test it?

**Comment by sweetpi** [comment]
I've only switches and no pilight installation.. I will release the new version.

**Pull request merged**
